storage:
  # If you have no MySQL server, Parcels will use SQLite instead. Just set mysql to false and ignore the rest.
  # If there's no password, use '' instead of null.
  mysql: true
  hostname: 'localhost:3306'
  database: 'example_db_name'
  username: 'username'
  password: 'password'

worlds:
  Parcels:
    # The amount of (active) parcels in each direction counting from the parcel with ID (0:0).
    parcel-axis-limit: 10

    # The (default) game mode of players that enter the world
    game-mode: CREATIVE
    
    # Whether to always keep the sun directly up there.
    static-time-day: true
    
    # Whether to keep the weather sunny.
    static-weather-clear: true

    # Whether breaking containers or killing a mob or hanging entity should drop its items
    drop-entity-items: false

    # The value of the gamerule doTileDrops: whether breaking blocks should yield item drops
    do-tile-drops: false
    
    interaction:
      # Whether to disable explosions in the world. If enabled, they will not destroy blocks or propel entities.
      # TNT Minecarts form an exception. These will damage and propel nearby entities, unfortunately.
      disable-explosions: true
      
      # Whether to disable portal creation.
      block-portal-creation: true
      
      # Whether to disable mob spawning.
      block-mob-spawning: true
      
      # Items whose use will be blocked. Right clicking while holding one of these items will be ignored.
      # For item names, see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
      # If you add an item, use the shown format without the # and remove the [].
      items-blocked: []
      #- FLINT_AND_STEEL
    
    generator:
      # The biome to use during the generation of the world.
      # See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html for biome names.
      default-biome: JUNGLE
    
      # Type ID first, Data value second. Data values can be excluded.
      wall-type: '44:6'
      floor-type: '35:8'
      fill-type: '35:7'
      path-main-type: '35:6'
      path-edge-type: '35:14'
      
      # The size of a parcel, both dimensions are the same.
      parcel-size: 101
      
      # The width of the path, including the wall blocks. 
      path-size: 8
      
      # The level the floor's at.
      floor-height: 63
      
      # Offset the world if you want to for whatever reason.
      offset-x: 0
      offset-z: 0

# For importing a world from PlotMe
import-plotme-settings:
  # If set to true, Parcels will import PlotMe
  # data from the SQL server on next start/reload.
  # enabled is set back to false afterwards,
  # regardless of success/fail.
  enabled: false
  
  # Worlds to import. Probably just one.
  # The first world is the name of the PlotMe world.
  # The world next to it is the name of the Parcel world.
  # You likely want these world names to be the same,
  # to keep the region data for plots. If they are, make
  # sure you have identical generator settings for your Parcel world.
  # It only makes sense to do this if you copy the world itself.
  
  worlds:
    plotworld: Parcels
  
  # When translating generator settings:
  # - PlotSize -> parcel-size
  # - PathWidth -> path-size
  # - GroundHeight -> floor-height
  # - XTranslation -> offset-x
  # - ZTranslation -> offset-z
  #
  # - WallBlock -> wall-type
  # - PlotFloorBlock -> floor-type
  # - FillBlock - fill-type
  # - RoadMainBlock -> path-main-type
  # - PathAltBlock -> path-edge-type